
name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 nbconvert

      - name: Lint with flake8
        run: |
          flake8 src/ --max-line-length=120

      - name: Run tests
        run: |
          pytest tests/

      - name: Test Jupyter notebooks (optional, quick check)
        run: |
          jupyter nbconvert --execute --inplace --to notebook notebooks/EDA_mimic.ipynb || true
